### ISSUE TITLE
Listeners' priority

### ISSUE THREAD

**Issue by fntlnz** [gianarb/fast-event-manager#2]
IMHO the `FastEventManager\EventManager`'s `attach` method signature should be something like

```
attach(string $event, callback $callback, int $priority)
```

where priority is not _mandatory_ and has a default value.

Undesired side effect: this will decrease the speed of the event manager :zap:

**Comment by gianarb** [comment]
IMO it is a very good enhancement! :) 
http://php.net/manual/en/class.splpriorityqueue.php ?? :)

**Comment by fntlnz** [comment]
The `SplPriorityQueue` is perfect for that!

**Comment by wdalmut** [comment]
:+1:
