### ISSUE TITLE
A simpler `trigger` API?

### ISSUE THREAD

**Issue by wdalmut** [gianarb/fast-event-manager#4]
Instead  of `trigger` with an `array` param use a different approach 

``` php
$em->trigger("/event/", $arg0, $arg1, $arg2);
```

Internally (php >= 5.3)

``` php
public function trigger($regex) {
    $args  = func_get_args();
    // call_user_func_array
}
```

Or increase the minimum php version to 5.6 with

``` php
public function trigger($regex, ...$args) {
    // call_user_func_array
}
```

Just an idea...

**Comment by gianarb** [comment]
Yes I tried this solution during my first implementation and IMO it is more readable! :+1: 

We can increase the php version >= 5.6 :) We are the future! :D

**Comment by gianarb** [comment]
I have a lot of problem with my mac and php 5.6.. WIP :) :)
